name: Snapshot Testing with Jest

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ '*' ]

jobs:
  jestci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        working-directory: ./mobile
        run: npm install
      - name: Run Snapshot tests with Jest
        working-directory: ./mobile
        run: npm run test